version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: oleffr/foodgram_backend
    env_file: .env
    volumes:
      - ./data/:/app/data
      - static:/static
      - media:/app/media
  frontend:
    image: oleffr/foodgram_frontend
    volumes:
      - static:/app/result_build/build/
  nginx:
    image: oleffr/foodgram_nginx
    env_file: .env
    ports:
      - "8090:80"
    volumes:
      - ./docs/:/var/www/html/api/docs/
      - static:/var/www/html/
      - media:/var/www/media/