version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: oleffr/foodgram_backend
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
  frontend:
    image: oleffr/foodgram_frontend
    command: cp -r /app/result_build/build/. /static/
    volumes:
      - static:/static/
  nginx:
    image: oleffr/foodgram_nginx
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    ports:
      - "8090:80"
    