version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    env_file: .env
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - ./data/:/app/data
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend

  frontend:
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/build/

  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - 8090:80
    volumes:
      - ./docs/:/var/www/html/api/docs/
      - static:/var/www/html/
      - media:/var/www/media/
    depends_on:
      - backend
      - frontend